name: Build Services

on:
  pull_request:
    branches:
      - "main"
    paths:
      - services/**
  push:
    branches:
      - main
    paths:
      - services/**

permissions:
  contents: read


jobs:
  get-changed-dirs:
    name: Get all changed directories
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-changed-dirs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get all changed dirs
        id: get-changed-dirs
        uses: ./.github/actions/get-changed-dirs
        with:
          paths: |
            services/**

  cicd:
    runs-on: ubuntu-latest
    needs: get-changed-dirs
    strategy:
      matrix: ${{ fromJSON(needs.get-changed-dirs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./${{ matrix.dirs }}/package-lock.json

      - name: Dependency install
        run: cd ./${{ matrix.dirs }} && npm install
        shell: bash

      - name: Static buid
        run: cd ./${{ matrix.dirs }} && npm run build
        shell: bash
